import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'
import App3 from './App3.vue'
import App2 from './App2.vue'
import App4 from './App4.vue'
import App5 from './App5.vue'
import App6 from './App6.vue'
import App7 from './app-config.vue'
import App9 from './App9.vue'
import App10 from './App10.vue'
import deepTable from './deepTable.vue'
import dropSort from './components/dropSort.vue'
import './styles/index.less'
import 'normalize.css'
import InitIcon from './icon'
createApp(App10).use(ElementPlus).use(InitIcon).mount('#app')
